spring:
  application:
    name:eureka-server

  cloud:
    compatibility-verifier:
      enabled: false
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
